### PR TITLE
fix(notice): allow popup/pin for domain_admin

### LINKED ISSUE #332: Add pinning and pop-up options when creating domain notice
Image

### PR DESCRIPTION
**Pull request by minseolee**
### To Reviewers
- [ ] Skip (`style`, `chore` ONLY)
- [x] Not that difficult

### Type of Change
- [ ] New feature
- [ ] Bug fixes
- [x] Feature improvement
- [ ] Refactor
- [ ] Others (performance improvement, refactoring, CI/CD, etc.)

### Checklist
- [x] `Error / Warning / Lint / Type`

### Description

스크린샷 2023-01-25 오후 6 47 38

Resolves #332 

Every feature is working fine. 

### Things to Talk About

There is a problem that,
`DOMAIN_VIEWER` would have `ADMIN_PERMISSION`.
So, `DOMAIN_VIEWER` can access to notice create page. 😱
But create api is not working for them 👍

### CODE REVIEW

File: src/lib/menu/menu-info.ts [hunk 1]
```diff
@@ -135,5 +135,6 @@ export const MENU_INFO_MAP: Record<MenuId, MenuInfo> = Object.freeze({
     [MENU_ID.INFO_NOTICE]: {
         translationId: 'MENU.INFO_NOTICE',
         isNew: true,
+        needPermissionByRole: true,
```
Comment (WANZARGEN) [inline src/lib/menu/menu-info.ts:138]: issue: If give true to `needPermissionByRole`, this menu will be exposed at [Role > Page Permission].

**Review by WANZARGEN — CHANGES_REQUESTED** [review]
Thanks for your hard work. I found a critical issue, so I left a comment. Please check it :)

File: src/lib/menu/menu-info.ts (hunk 1 above)
Comment (minseolee) [reply src/lib/menu/menu-info.ts:138]: Oh thanks I got it!

**Review by WANZARGEN — APPROVED** [review]
LGTM~

**Comment by minseolee** [comment]
It would be release on 1.11.0
